#!/usr/bin/env bash

if [[ -z "$HADOOP_HOME" ]]; then
  if [[ -d "etc/hadoop" ]]; then
    HADOOP_HOME="$PWD"
    echo "Set HADOOP_HOME to current directory $HADOOP_HOME" >&2
  else
    etc_hadoop=$(find hadoop-dist -path '**/etc/hadoop' 2>/dev/null)
    if [[ -d "$etc_hadoop" ]]; then
      HADOOP_HOME="$PWD/${etc_hadoop/\/etc\/hadoop//}"
      echo "Set HADOOP_HOME to $HADOOP_HOME in hadoop-dist" >&2
    else
      HADOOP_HOME="$HOME/hadoop"
      echo "Set HADOOP_HOME to default $HADOOP_HOME" >&2
    fi
  fi
else
  echo "HADOOP_HOME already set to $HADOOP_HOME" >&2
fi

echo "$HADOOP_HOME"
