#!/usr/bin/env bash

mydir=$(dirname $0)
myname=$(basename $0)

: ${TEST_SERVICES:=kms httpfs}
: ${TEST_CONFIG_DIR:=$mydir/config}

export HADOOP_KEYSTORE_PASSWORD=${HADOOP_KEYSTORE_PASSWORD:-password}

usage() {
  cat <<EOF
SYNOPSIS
  $myname start [<conf>]
  $myname restart [<conf>]
  $myname kill|stop
EOF
}

pseudo_dist_mode() {
  local action=$1
  local start_dfs
  local start_httpfs
  local start_kms

  for svc in ${TEST_SERVICES}; do
    case $svc in
      hdfs)
        start_dfs=yes
        ;;
      kms)
        start_kms=yes
        ;;
      httpfs)
        start_dfs=yes
        start_httpfs=yes
        ;;
      *)
        echo "Unknown service '$svc'" >&2
        exit 1
    esac
  done
 
  if [[ -f $mydir/scripts/test_helper.bash ]]; then
    . $mydir/scripts/test_helper.bash
    init_envs
  fi

  # For old httpfs.sh
  if [[ $HTTPFS_SSL_ENABLED == true ]]; then
    local httpfs_opts="-config conf/ssl-server.xml"
  fi

  # For old kms.sh
  if [[ $KMS_SSL_ENABLED == true ]]; then
    local kms_opts="-config conf/ssl-server.xml"
  fi

  # Make httpfs.sh happy
  if [[ -n $start_httpfs ]]; then
    mkdir -p $HADOOP_HOME/temp
  fi

  [[ -n $start_dfs ]] && $action-dfs.sh
  [[ -n $start_httpfs ]] && httpfs.sh $action $httpfs_opts
  [[ -n $start_kms ]] && kms.sh $action $kms_opts
}

copy_conf() {
  conf=$1
  [[ -z $conf ]] && return
  echo "Copying $TEST_CONFIG_DIR/$conf to $HADOOP_HOME/etc/hadoop"
  cp $TEST_CONFIG_DIR/$conf/* $HADOOP_HOME/etc/hadoop
  # Refresh test environment after copying the config files
}

if (( $# == 0 )); then
  usage
  exit
fi

while (( $# > 0 )); do
  case $1 in
    -h|--help)
      usage
      exit
      ;;
    kill|stop)
      pseudo_dist_mode stop
      jps
      ;;
    restart)
      pseudo_dist_mode stop
      copy_conf "$2"
      pseudo_dist_mode start
      jps
      shift # past argument
      ;;
    start)
      copy_conf "$2"
      pseudo_dist_mode start
      jps
      shift # past argument
      ;;
    -*)
      echo "Unknown option '$1'" >&2
      exit 1
      ;;
    *)
      echo "Unknown sub-command '$1'" >&2
      exit 1
      break
  esac
  shift
done
