#!/usr/bin/env bash

: ${HADOOP_HOME:=~/hadoop/hadoop-dist/target/hadoop-3.0.0-alpha2-SNAPSHOT}
export HADOOP_HOME
PATH=$HADOOP_HOME/sbin:$HADOOP_HOME/bin:$PATH


run_tests() {
  : ${SSL_ENABLED:=false}

  hdfs dfs -mkdir -p /tmp
  hdfs dfs -ls /

  httpfs_scheme=webhdfs
  [[ $SSL_ENABLED == true ]] && httpfs_scheme=swebhdfs
  hdfs dfs -ls $httpfs_scheme://localhost:14000/

  if [[ $SSL_ENABLED == false ]]; then
    hadoop daemonlog -getlevel localhost:9600 org.apache.hadoop.crypto.key.kms.server.KMS
    hadoop daemonlog -getlevel localhost:14000 org.apache.hadoop.fs.http.server.HttpFSServer
  fi

  hadoop key delete new1 -f >/dev/null 2>&1 || true
  hadoop key delete new2 -f >/dev/null 2>&1 || true

  hadoop key list
  hadoop key create new1
  hadoop key create new2
  hadoop key list
  hadoop key roll new1
  hadoop key delete new2 -f
  hadoop key list

  echo -e "\nALL tests passed !!!\n"
}

pseudo_dist_mode() {
  [[ -z "$@" ]] && return
  $1-dfs.sh
  hdfs --daemon $1 httpfs
  hadoop --daemon $1 kms
}

mydir=$(dirname $0)
conf=$1

set -ex

if [[ -n $conf ]]; then
  pseudo_dist_mode stop
  cp $mydir/$conf/* $HADOOP_HOME/etc/hadoop
  pseudo_dist_mode start
  jps
fi

test_env_file=$HADOOP_HOME/etc/hadoop/test_env
[[ -f $test_env_file ]] && . $test_env_file
run_tests
